# Note: this only runs manually or on pushes to tagged versions.

name: Publish STIsim docs

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    name: Quarto
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install STIsim
        run: pip install -e .[dev]

      - name: Pre-build font cache
        run: python -c "import stisim"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Quarto interlinks extension
        working-directory: ./docs
        run: quarto add machow/quartodoc --no-prompt

      - name: Custom Quarto publish
        working-directory: ./docs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          ./publish
